parameters:
  coreshop.form.type.checkout.address.validation_groups: [coreshop]
  coreshop.form.type.checkout.carrier.validation_groups: [coreshop]
  coreshop.form.type.checkout.payment.validation_groups: [coreshop]

services:
  coreshop.checkout_manager.default:
    class: CoreShop\Bundle\CoreBundle\Checkout\CheckoutManager

  #default steps
  coreshop.checkout.step.cart:
    class: CoreShop\Bundle\CoreBundle\Checkout\Step\CartCheckoutStep

  coreshop.checkout.step.customer:
    class: CoreShop\Bundle\CoreBundle\Checkout\Step\CustomerCheckoutStep
    arguments:
      - '@coreshop.context.customer'
      - '@form.factory'
      - '@coreshop.customer.registration_service'

  coreshop.checkout.step.address:
    class: CoreShop\Bundle\CoreBundle\Checkout\Step\AddressCheckoutStep
    arguments:
        - '@form.factory'
        - '@security.token_storage'
        - '@coreshop.cart.manager'

  coreshop.checkout.step.shipping:
    class: CoreShop\Bundle\CoreBundle\Checkout\Step\ShippingCheckoutStep
    arguments:
      - '@coreshop.carrier.discovery'
      - '@coreshop.shipping.carrier.validator'
      - '@form.factory'
      - '@coreshop.context.store'
      - '@coreshop.cart.manager'

  coreshop.checkout.step.payment:
    class: CoreShop\Bundle\CoreBundle\Checkout\Step\PaymentCheckoutStep
    arguments:
      - '@form.factory'
      - '@coreshop.context.store'
      - '@coreshop.cart.manager'

  coreshop.checkout.step.summary:
    class: CoreShop\Bundle\CoreBundle\Checkout\Step\SummaryCheckoutStep

  # Forms
  coreshop.form.type.checkout_address:
    class: CoreShop\Bundle\CoreBundle\Form\Type\Checkout\AddressType
    arguments:
      - '%coreshop.model.cart.class%'
      - '%coreshop.form.type.checkout.address.validation_groups%'
      - '@coreshop.address.formatter'
    tags:
      - {name: form.type}

  coreshop.form.type.checkout_payment:
    class: CoreShop\Bundle\CoreBundle\Form\Type\Checkout\PaymentType
    arguments:
      - '%coreshop.model.cart.class%'
      - '%coreshop.form.type.checkout.payment.validation_groups%'
    tags:
      - {name: form.type}

  coreshop.form.type.checkout_carrier:
    class: CoreShop\Bundle\CoreBundle\Form\Type\Checkout\CarrierType
    arguments:
      - '%coreshop.model.cart.class%'
      - '%coreshop.form.type.checkout.carrier.validation_groups%'
      - '@coreshop.carrier.price_calculator.taxed'
      - '@coreshop.context.currency'
      - '@coreshop.money_formatter'
      - '@coreshop.currency_converter'
      - '@coreshop.context.store'
      - '@pimcore.translator'

    tags:
      - {name: form.type}