services:
    coreshop.command.install.abstract:
        abstract: true
        class: CoreShop\Bundle\CoreBundle\Command\AbstractInstallCommand
        arguments:
            - '@kernel'
            - '@coreshop.installer.checker.command_directory'

    coreshop.command.install.assets:
        class: CoreShop\Bundle\CoreBundle\Command\AssetsInstallCommand
        parent: coreshop.command.install.abstract
        tags:
          - { name: console.command, command: 'coreshop:install:assets' }

    coreshop.command.install.classes:
        class: CoreShop\Bundle\CoreBundle\Command\InstallClassesCommand
        parent: coreshop.command.install.abstract
        tags:
          - { name: console.command, command: 'coreshop:install:classes' }

    coreshop.command.install.database:
        class: CoreShop\Bundle\CoreBundle\Command\InstallDatabaseCommand
        arguments:
            - '@kernel'
            - '@coreshop.installer.checker.command_directory'
            - '@coreshop.commands_provider.database_setup'
        tags:
          - { name: console.command, command: 'coreshop:install:database' }

    coreshop.command.install.demo:
        class: CoreShop\Bundle\CoreBundle\Command\InstallDemoCommand
        parent: coreshop.command.install.abstract
        tags:
          - { name: console.command, command: 'coreshop:install:demo' }

    coreshop.command.install.fixture:
        class: CoreShop\Bundle\CoreBundle\Command\InstallFixturesCommand
        parent: coreshop.command.install.abstract
        tags:
          - { name: console.command, command: 'coreshop:install:fixtures' }

    coreshop.command.install.folders:
        class: CoreShop\Bundle\CoreBundle\Command\InstallFoldersCommand
        arguments:
            - '@kernel'
            - '@coreshop.installer.checker.command_directory'
            - '@coreshop.installer.executor.folder_installer'
        tags:
          - { name: console.command, command: 'coreshop:install:folders' }

    coreshop.command.install:
        class: CoreShop\Bundle\CoreBundle\Command\InstallCommand
        parent: coreshop.command.install.abstract
        arguments:
            $migrationManager: '@Pimcore\Migrations\MigrationManager'
            $bundle: "@=service('kernel').getBundle('CoreShopCoreBundle')"
        tags:
          - { name: console.command, command: 'coreshop:install' }


    coreshop.command.check_rule_availability:
        class: CoreShop\Bundle\CoreBundle\Command\RuleAvailabilityCommand
        arguments:
            - '@coreshop.rule.availability_check'
        tags:
          - { name: console.command, command: 'coreshop:check-rule-availability' }