services:
  coreshop.form.extension.type.store:
    class: CoreShop\Bundle\CoreBundle\Form\Extension\StoreTypeExtension
    tags:
      - { name: form.type_extension, extended_type: CoreShop\Bundle\StoreBundle\Form\Type\StoreType }

  coreshop.form.extension.type.tax_rule:
    class: CoreShop\Bundle\CoreBundle\Form\Extension\TaxRuleTypeExtension
    tags:
      - { name: form.type_extension, extended_type: CoreShop\Bundle\TaxationBundle\Form\Type\TaxRuleType }

  coreshop.form.extension.type.tax_rule_group:
    class: CoreShop\Bundle\CoreBundle\Form\Extension\TaxRuleGroupTypeExtension
    tags:
      - { name: form.type_extension, extended_type: CoreShop\Bundle\TaxationBundle\Form\Type\TaxRuleGroupType }

  coreshop.form.extension.type.carrier:
    class: CoreShop\Bundle\CoreBundle\Form\Extension\CarrierTypeExtension
    tags:
      - { name: form.type_extension, extended_type: CoreShop\Bundle\ShippingBundle\Form\Type\CarrierType }

  coreshop.form.extension.type.country:
    class: CoreShop\Bundle\CoreBundle\Form\Extension\CountryTypeExtension
    tags:
      - { name: form.type_extension, extended_type: CoreShop\Bundle\AddressBundle\Form\Type\CountryType }

  coreshop.form.extension.type.payment_provider:
    class: CoreShop\Bundle\CoreBundle\Form\Extension\PaymentProviderTypeExtension
    tags:
      - { name: form.type_extension, extended_type: CoreShop\Bundle\PaymentBundle\Form\Type\PaymentProviderType }

  coreshop.form.type.address_choice:
    class: CoreShop\Bundle\CoreBundle\Form\Type\AddressChoiceType
    arguments: ['@coreshop.repository.customer']
    tags:
      - {name: form.type}