services:
    coreshop.data_object.grid_column_config.operator.factory.store_price:
        class: CoreShop\Bundle\CoreBundle\Pimcore\GridColumnConfig\Operator\Factory\StorePriceFactory
        arguments:
            - '@coreshop.repository.store'
            - '@coreshop.money_formatter'
        tags:
            - { name: pimcore.data_object.grid_column_config.operator_factory, id: StorePrice }

    coreshop.data_object.grid_column_config.list.listener.before_filter_prepare:
        class: CoreShop\Bundle\CoreBundle\EventListener\Order\Grid\ObjectListFilterListener
        arguments:
            - '@coreshop.registry.order_list_filter'
        tags:
            - { name: kernel.event_listener, event: pimcore.admin.object.list.beforeListLoad, method: checkObjectList }

    coreshop.registry.order_list_filter:
        class: CoreShop\Component\Registry\ServiceRegistry
        public: true
        arguments:
            - 'CoreShop\Component\Core\OrderList\OrderListFilterInterface'
            - 'coreshop-order-list-filter'

    coreshop.registry.order_list_bulk:
        class: CoreShop\Component\Registry\ServiceRegistry
        public: true
        arguments:
            - 'CoreShop\Component\Core\OrderList\OrderListBulkInterface'
            - 'coreshop-order-list-bulk'