services:
    _defaults:
        public: true

    CoreShop\Bundle\CoreBundle\Pimcore\GridColumnConfig\Operator\Factory\StorePriceFactory:
        arguments:
            - '@coreshop.repository.store'
            - '@coreshop.money_formatter'
        tags:
            - { name: pimcore.data_object.grid_column_config.operator_factory, id: StorePrice }
