services:
    _defaults:
        public: true

    coreshop.handler.shop_logout: '@CoreShop\Bundle\CoreBundle\EventListener\ShopUserLogoutHandler'
    CoreShop\Bundle\CoreBundle\EventListener\ShopUserLogoutHandler:
        arguments:
            - '@coreshop.link_generator'
            - '%coreshop.after_logout_redirect_route%'
            - '@session'
            - '@coreshop.context.store'
