services:
  coreshop.handler.shop_logout:
    class: CoreShop\Bundle\CoreBundle\EventListener\ShopUserLogoutHandler
    arguments:
      - '@security.http_utils'
      - '/'
      - '@session'
      - '@coreshop.context.store'
