services:
    coreshop.handler.shop_logout:
        class: CoreShop\Bundle\CoreBundle\EventListener\ShopUserLogoutHandler
        arguments:
            - '@router'
            - '%coreshop.after_logout_redirect_route%'
            - '@session'
            - '@coreshop.context.store'
