services:
    _defaults:
        public: true

    CoreShop\Bundle\CoreBundle\EventListener\ShopUserLogoutHandler:
        arguments:
            - '@router'
            - '%coreshop.after_logout_redirect_route%'
            - '@CoreShop\Component\Store\Context\StoreContextInterface'
