services:
    _defaults:
        public: true

    coreshop.inventory.order_operator:
      class: CoreShop\Component\Core\Inventory\Operator\OrderInventoryOperator
      arguments:
          - '@coreshop.manager.product'