services:
    _defaults:
        public: true

    coreshop.inventory.order_operator: '@CoreShop\Component\Core\Inventory\Operator\OrderInventoryOperator'
    CoreShop\Component\Core\Inventory\Operator\OrderInventoryOperator:
        arguments:
            - '@coreshop.manager.product'
