services:
  coreshop.listener.cart_blamer:
    class: CoreShop\Bundle\CoreBundle\EventListener\CartBlamerListener
    arguments:
      - '@coreshop.cart.manager'
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

  coreshop.listener.doctrine.okvpn_entity_resolver:
    class: CoreShop\Bundle\CoreBundle\EventListener\OkvpnEntityResolverListener
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata }