services:
    _defaults:
        public: true

    coreshop.context.locale.pimcore_admin: '@CoreShop\Component\Core\Locale\Context\PimcoreAdminLocaleContext'
    CoreShop\Component\Core\Locale\Context\PimcoreAdminLocaleContext:
        arguments:
            - '@Pimcore\Http\Request\Resolver\PimcoreContextResolver'
            - '@pimcore_admin.security.token_storage_user_resolver'
            - '@coreshop.translation_locale_provider'
            - '@request_stack'
        tags:
            - { name: coreshop.context.locale, priority: 300 }
