services:
  coreshop.core.order.transformer.cart_to_order:
    decorates: coreshop.order.transformer.cart_to_order
    class: CoreShop\Bundle\CoreBundle\Order\Transformer\CartToSaleTransformer
    arguments:
      - '@coreshop.core.order.transformer.cart_to_order.inner'
      - '@coreshop.currency_converter'

  coreshop.core.order.transformer.cart_to_quote:
    decorates: coreshop.order.transformer.cart_to_quote
    class: CoreShop\Bundle\CoreBundle\Order\Transformer\CartToSaleTransformer
    arguments:
      - '@coreshop.core.order.transformer.cart_to_quote.inner'
      - '@coreshop.currency_converter'

  coreshop.cart.cleanup.maintenance_listener:
    class: CoreShop\Bundle\CoreBundle\EventListener\CartCleanerMaintenanceManagerListener
    arguments:
      - '@coreshop.configuration.service'
      - '@coreshop.cart.cleanup'
    tags:
      - { name: kernel.event_listener, event: pimcore.system.maintenance, method: registerCartCleanup }
