services:
  coreshop.core.order.transformer.cart_to_order:
    decorates: coreshop.order.transformer.cart_to_order
    class: CoreShop\Bundle\CoreBundle\Order\Transformer\CartToSaleTransformer
    arguments:
      - '@coreshop.core.order.transformer.cart_to_order.inner'
      - '@coreshop.currency_converter'

  coreshop.core.order.transformer.cart_to_quote:
    decorates: coreshop.order.transformer.cart_to_quote
    class: CoreShop\Bundle\CoreBundle\Order\Transformer\CartToSaleTransformer
    arguments:
      - '@coreshop.core.order.transformer.cart_to_quote.inner'
      - '@coreshop.currency_converter'

  coreshop.cart.cleanup.maintenance_listener:
    class: CoreShop\Bundle\CoreBundle\EventListener\CartCleanerMaintenanceManagerListener
    arguments:
      - '@coreshop.configuration.service'
      - '@coreshop.cart.cleanup'
    tags:
      - { name: kernel.event_listener, event: pimcore.system.maintenance, method: registerCartCleanup }

  coreshop.order.number_generator.prefix_suffix:
    class: CoreShop\Bundle\CoreBundle\NumberGenerator\SaleNumberGenerator
    decorates: coreshop.order.number_generator.default
    arguments:
      - '@coreshop.order.number_generator.prefix_suffix.inner'
      - '@coreshop.configuration.service'
      - 'system.order.prefix'
      - 'system.order.suffix'

  coreshop.quote.number_generator.prefix_suffix:
    class: CoreShop\Bundle\CoreBundle\NumberGenerator\SaleNumberGenerator
    decorates: coreshop.quote.number_generator.default
    arguments:
      - '@coreshop.quote.number_generator.prefix_suffix.inner'
      - '@coreshop.configuration.service'
      - 'system.quote.prefix'
      - 'system.quote.suffix'

  coreshop.order_invoice.number_generator.prefix_suffix:
    class: CoreShop\Bundle\CoreBundle\NumberGenerator\SaleNumberGenerator
    decorates: coreshop.order_invoice.number_generator.default
    arguments:
      - '@coreshop.order_invoice.number_generator.prefix_suffix.inner'
      - '@coreshop.configuration.service'
      - 'system.invoice.prefix'
      - 'system.invoice.suffix'

  coreshop.order_shipment.number_generator.prefix_suffix:
    class: CoreShop\Bundle\CoreBundle\NumberGenerator\SaleNumberGenerator
    decorates: coreshop.order_shipment.number_generator.default
    arguments:
      - '@coreshop.order_shipment.number_generator.prefix_suffix.inner'
      - '@coreshop.configuration.service'
      - 'system.shipment.prefix'
      - 'system.shipment.suffix'

  coreshop.mail.processor.order:
    class: CoreShop\Component\Core\Order\OrderMailProcessor
    arguments:
     - '@coreshop.money_formatter'
     - '@coreshop.repository.order_invoice'
     - '@coreshop.repository.order_shipment'
     - '@coreshop.renderer.order.pdf'

  coreshop.renderer.order.pdf:
    class: CoreShop\Bundle\CoreBundle\Order\Renderer\OrderDocumentPdfRenderer
    arguments:
      - '@fragment.renderer.inline'
      - '@coreshop.configuration.service'
      - '@coreshop.renderer.pdf'

  coreshop.renderer.order.pdf.asset:
    class: CoreShop\Bundle\CoreBundle\Order\Renderer\AssetOrderDocumentPdfRenderer
    decorates: coreshop.renderer.order.pdf
    arguments: ['@coreshop.renderer.order.pdf.asset.inner']

  coreshop.event_listener.price_rule_update:
    class: CoreShop\Bundle\CoreBundle\EventListener\PriceRuleUpdateEventListener
    arguments: ['@coreshop.configuration.service']
    tags:
      - { name: kernel.event_listener, event: coreshop.cart_price_rule.post_save, method: storeConfigurationThatPriceRulesChanged }
      - { name: kernel.event_listener, event: coreshop.cart_price_rule.post_delete, method: storeConfigurationThatPriceRulesChanged }
      - { name: kernel.event_listener, event: coreshop.product_price_rule.post_save, method: storeConfigurationThatPriceRulesChanged }
      - { name: kernel.event_listener, event: coreshop.product_price_rule.post_delete, method: storeConfigurationThatPriceRulesChanged }

  coreshop.event_listener.product_update:
    class: CoreShop\Bundle\CoreBundle\EventListener\ProductUpdateEventListener
    arguments: ['@coreshop.configuration.service']
    tags:
      - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: storeConfigurationThatProductChanged }


  coreshop.event_listener.update_cart:
    class: CoreShop\Bundle\CoreBundle\EventListener\RequestCartRecalculation
    arguments:
     - '@coreshop.cart.manager'
     - '@coreshop.configuration.service'
     - '@pimcore.http.request_helper'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
