services:
  coreshop.core.order.transformer.cart_to_order:
    decorates: coreshop.order.transformer.cart_to_order
    class: CoreShop\Bundle\CoreBundle\Order\Transformer\CartToOrderTransformer
    arguments: ['@coreshop.core.order.transformer.cart_to_order.inner']