services:
    _defaults:
        public: true

    coreshop.form_registry.payment.settings:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    CoreShop\Component\Core\Payment\Resolver\StoreBasedPaymentProviderResolver:
        decoration_priority: 10
        decorates: CoreShop\Component\Payment\Resolver\PaymentProviderResolverInterface
        arguments:
            - '@coreshop.repository.payment_provider'
            - '@CoreShop\Component\Store\Context\StoreContextInterface'




