services:
  coreshop.registry.portlets:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - 'CoreShop\Component\Core\Portlet\PortletInterface'
      - 'coreshop-portlets'

  coreshop.portlets.order_cart:
    class: CoreShop\Bundle\CoreBundle\Portlet\OrderCartPortlet
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@coreshop.money_formatter'
      - '@coreshop.context.locale'
      - '%coreshop.pimcore_class_ids%'
    tags:
      - { name: coreshop.portlet, type: order_cart }

  coreshop.portlets.sales:
    class: CoreShop\Bundle\CoreBundle\Portlet\SalesPortlet
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@coreshop.money_formatter'
      - '@coreshop.context.locale'
      - '%coreshop.pimcore_class_ids%'
    tags:
      - { name: coreshop.portlet, type: sales }