services:
    _defaults:
        public: true

    coreshop.product.tax_factory: '@CoreShop\Component\Core\Product\ProductTaxCalculatorFactory'
    CoreShop\Component\Core\Product\ProductTaxCalculatorFactory:
        arguments:
            - '@coreshop.taxation.factory.tax_calculator'
            - '@coreshop.factory.address'

    coreshop.product.taxed_price_calculator: '@CoreShop\Component\Core\Product\TaxedProductPriceCalculator'
    CoreShop\Component\Core\Product\TaxedProductPriceCalculator:
        arguments:
            - '@coreshop.order.purchasable.calculator'
            - '@coreshop.provider.taxation.default_country'
            - '@coreshop.product.tax_factory'
            - '@coreshop.taxation.tax_applicator'

    CoreShop\Bundle\CoreBundle\Templating\Helper\ProductPriceHelperInterface: '@CoreShop\Bundle\CoreBundle\Templating\Helper\ProductPriceHelper'
    CoreShop\Bundle\CoreBundle\Templating\Helper\ProductPriceHelper:
        arguments:
            - '@coreshop.product.taxed_price_calculator'
            - '@coreshop.context.shopper'
        tags:
            - { name: templating.helper, alias: coreshop_product_price }

    CoreShop\Bundle\CoreBundle\Templating\Helper\ProductQuantityPriceRuleRangesPriceHelperInterface: '@CoreShop\Bundle\CoreBundle\Templating\Helper\ProductQuantityPriceRuleRangesPriceHelper'
    CoreShop\Bundle\CoreBundle\Templating\Helper\ProductQuantityPriceRuleRangesPriceHelper:
        arguments:
            - '@CoreShop\Component\ProductQuantityPriceRules\Detector\QuantityReferenceDetector'
            - '@coreshop.order.purchasable.calculator'
            - '@coreshop.provider.taxation.default_country'
            - '@coreshop.product.tax_factory'
            - '@coreshop.taxation.tax_applicator'
        tags:
            - { name: templating.helper, alias: coreshop_product_tax }

    CoreShop\Bundle\CoreBundle\Templating\Helper\ProductTaxHelperInterface: '@CoreShop\Bundle\CoreBundle\Templating\Helper\ProductTaxHelper'
    CoreShop\Bundle\CoreBundle\Templating\Helper\ProductTaxHelper:
        arguments:
            - '@CoreShop\Bundle\CoreBundle\Templating\Helper\ProductPriceHelper'
            - '@coreshop.context.shopper'
            - '@coreshop.product.tax_factory'
            - '@coreshop.provider.taxation.default_country'
        tags:
            - { name: templating.helper, alias: coreshop_product_tax }

    CoreShop\Bundle\CoreBundle\Twig\ProductPriceExtension:
        arguments:
            - '@CoreShop\Bundle\CoreBundle\Templating\Helper\ProductPriceHelper'
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\CoreBundle\Twig\ProductQuantityPriceRuleRangesPriceExtension:
        arguments:
            - '@CoreShop\Bundle\CoreBundle\Templating\Helper\ProductQuantityPriceRuleRangesPriceHelper'
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\CoreBundle\Twig\ProductTaxExtension:
        arguments:
            - '@CoreShop\Bundle\CoreBundle\Templating\Helper\ProductTaxHelper'
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\CoreBundle\Templating\Helper\ConfigurationHelperInterface: '@CoreShop\Bundle\CoreBundle\Templating\Helper\ConfigurationHelper'
    CoreShop\Bundle\CoreBundle\Templating\Helper\ConfigurationHelper:
        arguments:
            - '@coreshop.configuration.service'
        tags:
            - { name: templating.helper, alias: coreshop_configuration}

    CoreShop\Bundle\CoreBundle\Twig\ConfigurationExtension:
        arguments:
            - '@CoreShop\Bundle\CoreBundle\Templating\Helper\ConfigurationHelper'
        tags:
            - { name: twig.extension }

    coreshop.product.price_calculator.property_price: '@CoreShop\Component\Core\Product\Calculator\StoreProductPriceCalculator'
    CoreShop\Component\Core\Product\Calculator\StoreProductPriceCalculator:
        tags:
            - { name: coreshop.product.retail_price_calculator, type: store_price, priority: 10 }

    coreshop.product.price_calculator.unit_price: '@CoreShop\Component\Core\Product\Calculator\StoreProductUnitDefinitionPriceCalculator'
    CoreShop\Component\Core\Product\Calculator\StoreProductUnitDefinitionPriceCalculator:
        tags:
            - { name: coreshop.product.retail_price_calculator, type: store_unit_price, priority: 11 }

    coreshop.order.purchasable.price_calculator.product: '@CoreShop\Component\Core\Order\Calculator\PurchasableProductPriceCalculator'
    CoreShop\Component\Core\Order\Calculator\PurchasableProductPriceCalculator:
        arguments:
            - '@coreshop.product.price_calculator'
        tags:
            - { name: coreshop.order.purchasable.price_calculator, type: product, priority: 20 }

    coreshop.order.purchasable.retail_price_calculator.product: '@CoreShop\Component\Core\Order\Calculator\PurchasableProductRetailPriceCalculator'
    CoreShop\Component\Core\Order\Calculator\PurchasableProductRetailPriceCalculator:
        arguments:
            - '@coreshop.product.price_calculator'
        tags:
            - { name: coreshop.order.purchasable.retail_price_calculator, type: product, priority: 20 }

    coreshop.order.purchasable.discount_calculator.product: '@CoreShop\Component\Core\Order\Calculator\PurchasableProductDiscountCalculator'
    CoreShop\Component\Core\Order\Calculator\PurchasableProductDiscountCalculator:
        arguments:
            - '@coreshop.product.price_calculator'
        tags:
            - { name: coreshop.order.purchasable.discount_calculator, type: product, priority: 20 }

    coreshop.order.purchasable.discount_price_calculator.product: '@CoreShop\Component\Core\Order\Calculator\PurchasableProductDiscountPriceCalculator'
    CoreShop\Component\Core\Order\Calculator\PurchasableProductDiscountPriceCalculator:
        arguments:
            - '@coreshop.product.price_calculator'
        tags:
            - { name: coreshop.order.purchasable.discount_price_calculator, type: product, priority: 20 }
