parameters:
    coreshop.form.type.product_store_values.validation_groups: [coreshop]

services:
    # Forms
    coreshop.form.type.product_store_values:
        class: CoreShop\Bundle\CoreBundle\Form\Type\Product\ProductStoreValuesType
        arguments:
            - '%coreshop.model.product_store_values.class%'
            - '%coreshop.form.type.product_store_values.validation_groups%'
        tags:
            - { name: form.type }
