services:
  coreshop.product_price_rule.condition.quantity:
    class: CoreShop\Bundle\CoreBundle\Product\ProductPriceRule\Condition\QuantityConditionChecker
    arguments:
      - '@coreshop.cart.manager'
    tags:
      - { name: coreshop.product_price_rule.condition, type: quantity, form-type: CoreShop\Bundle\CoreBundle\Form\Type\ProductPriceRule\Condition\QuantityConfigurationType }

  coreshop.product.tax_factory:
    class: CoreShop\Component\Core\Product\ProductTaxCalculatorFactory
    arguments:
      - '@coreshop.taxation.factory.tax_calculator'
      - '@coreshop.factory.address'
      - '@coreshop.context.country'

  coreshop.product.taxed_price_calculator:
    class: CoreShop\Component\Core\Product\TaxedProductPriceCalculator
    arguments:
      - '@coreshop.product.price_calculator'
      - '@coreshop.product.tax_factory'

  coreshop.templating.helper.price:
    class: CoreShop\Bundle\CoreBundle\Templating\Helper\ProductPriceHelper
    arguments: ['@coreshop.product.taxed_price_calculator']
    tags:
      - { name: templating.helper, alias: coreshop_product_price}

  coreshop.twig.extension.price:
    class: CoreShop\Bundle\CoreBundle\Twig\ProductPriceExtension
    arguments: ['@coreshop.templating.helper.price']
    tags:
      - { name: twig.extension }