services:
    _defaults:
        public: true

    coreshop.registry.reports:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - 'CoreShop\Component\Core\Report\ReportInterface'
            - 'coreshop-reports'

    coreshop.registry.portlets:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - 'CoreShop\Component\Core\Portlet\PortletInterface'
            - 'coreshop-portlets'

    coreshop.report.products: '@CoreShop\Bundle\CoreBundle\Report\ProductsReport'
    CoreShop\Bundle\CoreBundle\Report\ProductsReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.money_formatter'
            - '@coreshop.context.locale'
            - '@coreshop.repository.order'
            - '@coreshop.repository.order_item'
            - '@coreshop.repository.stack.product'
        tags:
            - { name: coreshop.report, type: products }

    coreshop.report.categories: '@CoreShop\Bundle\CoreBundle\Report\CategoriesReport'
    CoreShop\Bundle\CoreBundle\Report\CategoriesReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.money_formatter'
            - '@coreshop.context.locale'
            - '@coreshop.repository.order'
            - '@coreshop.repository.category'
            - '@coreshop.repository.order_item'
        tags:
            - { name: coreshop.report, type: categories }

    coreshop.report.customers: '@CoreShop\Bundle\CoreBundle\Report\CustomersReport'
    CoreShop\Bundle\CoreBundle\Report\CustomersReport:
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@coreshop.money_formatter'
            - '@coreshop.context.locale'
            - '@coreshop.repository.order'
            - '@coreshop.repository.customer'
        tags:
            - { name: coreshop.report, type: customers }

    coreshop.report.carts: '@CoreShop\Bundle\CoreBundle\Report\CartsReport'
    CoreShop\Bundle\CoreBundle\Report\CartsReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.repository.order'
            - '@coreshop.repository.cart'
        tags:
            - { name: coreshop.report, type: carts }
            - { name: coreshop.portlet, type: order_cart }

    coreshop.report.carts_abandoned: '@CoreShop\Bundle\CoreBundle\Report\AbandonedCartsReport'
    CoreShop\Bundle\CoreBundle\Report\AbandonedCartsReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.repository.cart'
            - '@coreshop.repository.customer'
            - '@coreshop.context.locale'
        tags:
            - { name: coreshop.report, type: carts_abandoned }

    coreshop.report.manufacturer: '@CoreShop\Bundle\CoreBundle\Report\ManufacturerReport'
    CoreShop\Bundle\CoreBundle\Report\ManufacturerReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.money_formatter'
            - '@coreshop.context.locale'
            - '@coreshop.repository.manufacturer'
            - '@coreshop.repository.order'
            - '@coreshop.repository.order_item'
        tags:
            - { name: coreshop.report, type: manufacturer }

    coreshop.report.sales: '@CoreShop\Bundle\CoreBundle\Report\SalesReport'
    CoreShop\Bundle\CoreBundle\Report\SalesReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.money_formatter'
            - '@coreshop.context.locale'
            - '@coreshop.repository.order'
        tags:
            - { name: coreshop.report, type: sales }
            - { name: coreshop.portlet, type: sales }

    coreshop.report.carriers: '@CoreShop\Bundle\CoreBundle\Report\CarriersReport'
    CoreShop\Bundle\CoreBundle\Report\CarriersReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.repository.carrier'
            - '@coreshop.repository.order'
        tags:
            - { name: coreshop.report, type: carriers }

    coreshop.report.payment_providers: '@CoreShop\Bundle\CoreBundle\Report\PaymentProvidersReport'
    CoreShop\Bundle\CoreBundle\Report\PaymentProvidersReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.repository.payment_provider'
            - '@coreshop.repository.order'
        tags:
            - { name: coreshop.report, type: payment_providers }

    coreshop.report.vouchers: '@CoreShop\Bundle\CoreBundle\Report\VouchersReport'
    CoreShop\Bundle\CoreBundle\Report\VouchersReport:
        arguments:
            - '@coreshop.repository.store'
            - '@doctrine.dbal.default_connection'
            - '@coreshop.money_formatter'
            - '@coreshop.context.locale'
            - '@coreshop.repository.order'
        tags:
            - { name: coreshop.report, type: vouchers }
