services:
    coreshop.rule.condition.customers:
        class: CoreShop\Component\Core\Product\Rule\Condition\CustomersConditionChecker
        arguments:
            - '@coreshop.context.customer'
        tags:
            - { name: coreshop.shipping_rule.condition, type: customers, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomersConfigurationType }
            - { name: coreshop.product_price_rule.condition, type: customers, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomersConfigurationType }
            - { name: coreshop.product_specific_price_rule.condition, type: customers, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomersConfigurationType }

    coreshop.rule.condition.customer_groups:
        class: CoreShop\Component\Core\Product\Rule\Condition\CustomerGroupsConditionChecker
        arguments:
            - '@coreshop.context.customer'
        tags:
            - { name: coreshop.shipping_rule.condition, type: customerGroups, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomerGroupsConfigurationType }
            - { name: coreshop.product_price_rule.condition, type: customerGroups, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomerGroupsConfigurationType }
            - { name: coreshop.product_specific_price_rule.condition, type: customerGroups, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomerGroupsConfigurationType }

    coreshop.rule.condition.countries:
        class: CoreShop\Component\Core\Product\Rule\Condition\CountriesConditionChecker
        arguments:
            - '@coreshop.context.country'
        tags:
            - { name: coreshop.product_price_rule.condition, type: countries, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CountriesConfigurationType }
            - { name: coreshop.product_specific_price_rule.condition, type: countries, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CountriesConfigurationType }

    coreshop.rule.condition.zones:
        class: CoreShop\Component\Core\Product\Rule\Condition\ZonesConditionChecker
        arguments:
            - '@coreshop.context.country'
        tags:
            - { name: coreshop.product_price_rule.condition, type: zones, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\ZonesConfigurationType }
            - { name: coreshop.product_specific_price_rule.condition, type: zones, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\ZonesConfigurationType }

    coreshop.rule.condition.stores:
        class: CoreShop\Component\Core\Product\Rule\Condition\StoresConditionChecker
        arguments:
            - '@coreshop.context.store'
        tags:
            - { name: coreshop.shipping_rule.condition, type: stores, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\StoresConfigurationType }
            - { name: coreshop.product_price_rule.condition, type: stores, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\StoresConfigurationType }
            - { name: coreshop.product_specific_price_rule.condition, type: stores, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\StoresConfigurationType }

    coreshop.rule.condition.currencies:
        class: CoreShop\Component\Core\Product\Rule\Condition\CurrenciesConditionChecker
        arguments:
            - '@coreshop.context.currency'
        tags:
            - { name: coreshop.shipping_rule.condition, type: currencies, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CurrenciesConfigurationType }
            - { name: coreshop.product_price_rule.condition, type: currencies, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CurrenciesConfigurationType }
            - { name: coreshop.product_specific_price_rule.condition, type: currencies, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CurrenciesConfigurationType }

    # Cart Price Rules
    coreshop.rule.cart_price_rule.condition.customers:
        class: CoreShop\Component\Core\Cart\Rule\Condition\CustomersConditionChecker
        tags:
            - { name: coreshop.cart_price_rule.condition, type: customers, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomersConfigurationType }

    coreshop.rule.cart_price_rule.condition.customer_groups:
        class: CoreShop\Component\Core\Cart\Rule\Condition\CustomerGroupsConditionChecker
        tags:
            - { name: coreshop.cart_price_rule.condition, type: customerGroups, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CustomerGroupsConfigurationType }

    coreshop.rule.cart_price_rule.condition.countries:
        class: CoreShop\Component\Core\Cart\Rule\Condition\CountriesConditionChecker
        tags:
            - { name: coreshop.cart_price_rule.condition, type: countries, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CountriesConfigurationType }

    coreshop.rule.cart_price_rule.condition.zones:
        class: CoreShop\Component\Core\Cart\Rule\Condition\ZonesConditionChecker
        tags:
            - { name: coreshop.cart_price_rule.condition, type: zones, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\ZonesConfigurationType }

    coreshop.rule.cart_price_rule.condition.stores:
        class: CoreShop\Component\Core\Cart\Rule\Condition\StoresConditionChecker
        tags:
            - { name: coreshop.cart_price_rule.condition, type: stores, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\StoresConfigurationType }

    coreshop.rule.cart_price_rule.condition.currencies:
        class: CoreShop\Component\Core\Cart\Rule\Condition\CurrenciesConditionChecker
        tags:
            - { name: coreshop.cart_price_rule.condition, type: currencies, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CurrenciesConfigurationType }

    coreshop.rule.cart_price_rule.condition.carriers:
        class: CoreShop\Component\Core\Cart\Rule\Condition\CarriersConditionChecker
        tags:
            - { name: coreshop.cart_price_rule.condition, type: carriers, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CarriersConfigurationType }

    coreshop.rule.cart_price_rule.action.free_shipping:
        class: CoreShop\Component\Core\Cart\Rule\Action\FreeShippingActionProcessor
        tags:
            - { name: coreshop.cart_price_rule.action, type: freeShipping, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Action\FreeShippingConfigurationType }

    coreshop.rule.cart_price_rule.action.gift_product:
        class: CoreShop\Component\Core\Cart\Rule\Action\GiftProductActionProcessor
        arguments:
            - '@coreshop.repository.product'
            - '@coreshop.cart.modifier'
        tags:
            - { name: coreshop.cart_price_rule.action, type: giftProduct, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Action\GiftProductConfigurationType }