services:
    _defaults:
        public: true

    CoreShop\Bundle\CoreBundle\Controller\SettingsController:
        arguments:
          $viewHandler: '@CoreShop\Bundle\ResourceBundle\Controller\ViewHandlerInterface'
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\ReportsController:
        arguments:
            $viewHandler: '@CoreShop\Bundle\ResourceBundle\Controller\ViewHandlerInterface'
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\PortletsController:
        arguments:
            $viewHandler: '@CoreShop\Bundle\ResourceBundle\Controller\ViewHandlerInterface'
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\ProductValidationController:
        arguments:
            $viewHandler: '@CoreShop\Bundle\ResourceBundle\Controller\ViewHandlerInterface'
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\ProductVariantUnitSolidifierController:
        arguments:
            $viewHandler: '@CoreShop\Bundle\ResourceBundle\Controller\ViewHandlerInterface'
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\CustomerTransformerController:
        arguments:
            $viewHandler: '@CoreShop\Bundle\ResourceBundle\Controller\ViewHandlerInterface'
        tags:
            - { name: container.service_subscriber }
