services:
    _defaults:
        public: true

    CoreShop\Bundle\CoreBundle\Controller\SettingsController:
        arguments:
          - '@coreshop.resource_controller.view_handler'
        calls:
          - [setContainer, ['@service_container']]

    CoreShop\Bundle\CoreBundle\Controller\ReportsController:
        arguments:
          - '@coreshop.resource_controller.view_handler'
        calls:
          - [setContainer, ['@service_container']]

    CoreShop\Bundle\CoreBundle\Controller\PortletsController:
        arguments:
          - '@coreshop.resource_controller.view_handler'
        calls:
          - [setContainer, ['@service_container']]

    CoreShop\Bundle\CoreBundle\Controller\ProductPreviewController:
        arguments:
            - '@coreshop.resource_controller.view_handler'
        calls:
            - [setContainer, ['@service_container']]
