services:
    _defaults:
        public: true

    CoreShop\Bundle\CoreBundle\Controller\SettingsController:
        parent: CoreShop\Bundle\ResourceBundle\Controller\AdminController
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\ReportsController:
        parent: CoreShop\Bundle\ResourceBundle\Controller\AdminController
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\PortletsController:
        parent: CoreShop\Bundle\ResourceBundle\Controller\AdminController
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\ProductValidationController:
        parent: CoreShop\Bundle\ResourceBundle\Controller\AdminController
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\ProductVariantUnitSolidifierController:
        parent: CoreShop\Bundle\ResourceBundle\Controller\AdminController
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\CoreBundle\Controller\CustomerTransformerController:
        parent: CoreShop\Bundle\ResourceBundle\Controller\AdminController
        tags:
            - { name: container.service_subscriber }
