services:
    coreshop.carrier.price_calculator.free_shipping_rule:
        class: CoreShop\Component\Core\Shipping\Calculator\FreeShippingPriceRuleActionCalculator
        tags:
            - { name: coreshop.shipping.price_calculator, type: free-shipping-rule, priority: 255 }

    coreshop.shipping_rule.condition.categories:
        class: CoreShop\Component\Core\Shipping\Rule\Condition\CategoriesConditionChecker
        arguments:
            - '@coreshop.repository.category'
            - '@coreshop.context.store'
        tags:
            - { name: coreshop.shipping_rule.condition, type: categories, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CategoriesConfigurationType }

    coreshop.shipping_rule.condition.products:
        class: CoreShop\Component\Core\Shipping\Rule\Condition\ProductsConditionChecker
        tags:
            - { name: coreshop.shipping_rule.condition, type: products, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\ProductsConfigurationType }

    coreshop.shipping_rule.condition.countries:
        class: CoreShop\Component\Core\Shipping\Rule\Condition\CountriesConditionChecker
        tags:
            - { name: coreshop.shipping_rule.condition, type: countries, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CountriesConfigurationType }

    coreshop.shipping_rule.condition.zones:
        class: CoreShop\Component\Core\Shipping\Rule\Condition\ZonesConditionChecker
        tags:
            - { name: coreshop.shipping_rule.condition, type: zones, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\ZonesConfigurationType }

    coreshop.carrier.price_calculator.taxed:
        class: CoreShop\Component\Core\Shipping\Calculator\TaxedCarrierPriceRuleCalculator
        arguments:
            - '@coreshop.carrier.price_calculator.default'
            - '@coreshop.taxation.factory.tax_calculator'
            - '@coreshop.taxation.tax_applicator'

    coreshop.carrier.cart.store_based_resolver:
        class: CoreShop\Component\Core\Shipping\Discover\StoreBasedShippableCarriersDiscovery
        decorates: coreshop.carrier.resolver
        arguments:
            - '@coreshop.repository.carrier'
            - '@coreshop.shipping.carrier.validator'
            - '@coreshop.context.store'