services:
  coreshop.carrier.price_calculator.free_shipping_rule:
    class: CoreShop\Bundle\CoreBundle\Shipping\Calculator\FreeShippingPriceRuleActionCalculator
    tags:
      - { name: coreshop.shipping.price_calculator, type: free-shipping-rule, priority: 255 }

  coreshop.shipping_rule.condition.categories:
    class: CoreShop\Component\Core\Shipping\Rule\Condition\CategoriesConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: categories, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CategoriesConfigurationType }

  coreshop.shipping_rule.condition.products:
    class: CoreShop\Component\Core\Shipping\Rule\Condition\ProductsConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: products, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\ProductsConfigurationType }

  coreshop.carrier.price_calculator.taxed:
    class: CoreShop\Bundle\CoreBundle\Shipping\Calculator\TaxedCarrierPriceRuleCalculator
    decorates: coreshop.carrier.price_calculator
    arguments:
      - '@coreshop.carrier.price_calculator.taxed.inner'
      - '@coreshop.taxation.factory.tax_calculator'