services:
    _defaults:
        public: true

    coreshop.tracking.item_builder.decorated:
        class: CoreShop\Bundle\CoreBundle\Tracking\Builder\ItemBuilder
        decorates: coreshop.tracking.item_builder
        arguments:
            - '@coreshop.tracking.item_builder.decorated.inner'
            - '@coreshop.product.taxed_price_calculator'