services:
    _defaults:
        public: true

    coreshop.tracking.extractor.order:
        class: CoreShop\Component\Core\Tracking\Extractor\OrderExtractor
        arguments:
            - '@coreshop.tracking.extractor'
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: coreshop.tracking.extractor, type: order }

    coreshop.tracking.extractor.order_item:
        class: CoreShop\Component\Core\Tracking\Extractor\OrderItemExtractor
        arguments:
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: coreshop.tracking.extractor, type: order-item }

    coreshop.tracking.extractor.purchasable:
        class: CoreShop\Component\Core\Tracking\Extractor\ProductExtractor
        arguments:
            - '@coreshop.product.taxed_price_calculator'
            - '@coreshop.context.shopper'
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: coreshop.tracking.extractor, type: product }