services:
    CoreShop\Bundle\CoreBundle\Validator\Constraints\AddToCartAvailabilityValidator:
        arguments:
            - '@coreshop.inventory.availability_checker'
        tags:
            - { name: validator.constraint_validator, alias: coreshop_add_to_cart_availability }

    CoreShop\Bundle\CoreBundle\Validator\Constraints\CartStockAvailabilityValidator:
        arguments:
            - '@coreshop.inventory.availability_checker'
        tags:
            - { name: validator.constraint_validator, alias: coreshop_cart_stock_availability }

    coreshop.validator.quantity_validator: '@CoreShop\Bundle\CoreBundle\Validator\QuantityValidatorService'
    CoreShop\Bundle\CoreBundle\Validator\QuantityValidatorService: ~

    CoreShop\Bundle\CoreBundle\Validator\Constraints\AddToCartQuantityValidator:
        arguments:
            - '@CoreShop\Bundle\CoreBundle\Validator\QuantityValidatorService'
        tags:
            - { name: validator.constraint_validator, alias: coreshop_add_to_cart_quantity }

    CoreShop\Bundle\CoreBundle\Validator\Constraints\CartQuantityValidator:
        arguments:
            - '@CoreShop\Bundle\CoreBundle\Validator\QuantityValidatorService'
        tags:
            - { name: validator.constraint_validator, alias: coreshop_cart_quantity }
