CoreShop\Component\Core\Model\Payment:
    type: mappedSuperclass
    table: coreshop_payment
    fields:
        order:
            column: '`order`'
            type: pimcoreObject
    manyToOne:
        currency:
            targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
            joinColumn:
                name: currency_id
                referencedColumnName: id
                nullable: true
                onDelete: 'SET NULL'
