CoreShop\Component\Core\Model\ProductStoreValues:
    type: mappedSuperclass
    table: coreshop_product_store_values
    fields:
        id:
            type: integer
            column: id
            id: true
            generator:
                strategy: AUTO
        product:
            column: product
            type: pimcoreObject
        price:
            column: price
            type: integer
    manyToOne:
        store:
            targetEntity: CoreShop\Component\Store\Model\StoreInterface
            joinColumn:
                name: store
                referencedColumnName: id
                onDelete: 'SET NULL'
    oneToMany:
        productUnitDefinitionPrices:
            targetEntity: CoreShop\Component\Core\Model\ProductUnitDefinitionPriceInterface
            mappedBy: productStoreValues
            orphanRemoval: true
            cascade:
                - 'all'
    uniqueConstraints:
        product_store:
            columns: [product, store]