CoreShop\Component\Core\Model\ProductUnitDefinitionPrice:
    type: mappedSuperclass
    table: coreshop_product_unit_definition_price
    manyToOne:
        productStoreValues:
            targetEntity: CoreShop\Component\Core\Model\ProductStoreValuesInterface
            inversedBy: productUnitDefinitionPrices
            joinColumn:
                name: product_store_values
                referencedColumnName: id
                onDelete: CASCADE
    uniqueConstraints:
        store_values_unit_definition:
            columns: [product_store_values, unit_definition]