CoreShop\Component\Core\Model\ProductStoreValues:
    type: mappedSuperclass
    table: coreshop_product_store_values
    fields:
        id:
            type: integer
            column: id
            id: true
            generator:
                strategy: AUTO
        product:
            column: product
            type: pimcoreObject
        price:
            column: price
            type: integer
    manyToOne:
        store:
            targetEntity: CoreShop\Component\Store\Model\StoreInterface
            joinColumn:
                name: store
                referencedColumnName: id
                onDelete: 'SET NULL'
    oneToOne:
        defaultUnitDefinition:
            targetEntity: CoreShop\Component\Product\Model\ProductUnitDefinitionInterface
            cascade:
                - 'persist'
            orphanRemoval: true
            joinColumn:
                name: default_unit_definition
                referencedColumnName: id
                nullable: true
                onDelete: 'SET NULL'
    manyToMany:
        unitDefinitions:
            targetEntity: CoreShop\Component\Product\Model\ProductUnitDefinitionInterface
            cascade:
                - 'all'
            orphanRemoval: true
            joinTable:
                name: coreshop_product_unit_definitions
                joinColumns:
                    product_store_values_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
                inverseJoinColumns:
                    unit_definition_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
    uniqueConstraints:
        product_store:
            columns: [product, store]