CoreShop\Component\Core\Model\QuantityRange:
    type: mappedSuperclass
    table: coreshop_product_quantity_price_rule_range
    fields:
        amount:
            column: amount
            type: integer
        pseudoPrice:
            column: pseudo_price
            type: integer
    manyToOne:
        currency:
            targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
            joinColumn:
                name: currencyId
                referencedColumnName: id
                onDelete: 'SET NULL'
    oneToOne:
        unitDefinition:
            targetEntity: CoreShop\Component\Product\Model\ProductUnitDefinitionInterface
            joinColumn:
                name: unit
                referencedColumnName: id
                nullable: true