CoreShop\Component\Core\Model\QuantityRange:
    type: mappedSuperclass
    table: coreshop_product_quantity_price_rule_range
    fields:
        amount:
            column: amount
            type: bigint
        pseudoPrice:
            column: pseudo_price
            type: bigint
    manyToOne:
        currency:
            targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
            joinColumn:
                name: currencyId
                referencedColumnName: id
                onDelete: 'SET NULL'
        unitDefinition:
            targetEntity: CoreShop\Component\Product\Model\ProductUnitDefinitionInterface
            joinColumn:
                name: unit_definition
                referencedColumnName: id