CoreShop\Component\Core\Model\Store:
  type: mappedSuperclass
  table: coreshop_store
  manyToOne:
    baseCountry:
      targetEntity: CoreShop\Component\Address\Model\CountryInterface
      joinColumn:
        name: baseCountryId
        referencedColumnName: id
        nullable: true
      fetch: EAGER