CoreShop\Component\Core\Model\Store:
  type: mappedSuperclass
  table: coreshop_store
  manyToOne:
    baseCountry:
      targetEntity: CoreShop\Component\Address\Model\CountryInterface
      joinColumn:
        name: baseCountryId
        referencedColumnName: id
        nullable: true
      fetch: EAGER
  oneToMany:
    configurations:
      targetEntity: CoreShop\Component\Configuration\Model\ConfigurationInterface
      orphanRemoval: true
      mappedBy: store
      cascade: [ persist, remove ]
      fetch: EAGER
  manyToMany:
    countries:
      targetEntity: CoreShop\Component\Address\Model\CountryInterface
      mappedBy: stores
      cascade:
        - remove
    taxRuleGroups:
      targetEntity: CoreShop\Component\Taxation\Model\TaxRuleGroupInterface
      mappedBy: stores
      cascade:
        - remove