pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopStorePrice: CoreShop\Bundle\CoreBundle\CoreExtension\StorePrice

imports:
    - { resource: "@CoreShopCoreBundle/Resources/config/app/config.yml" }