payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"

coreshop_admin_payment_provider_config:
    path: /%coreshop.admin.route.base%/payment_providers/get-config
    defaults: { _controller: 'coreshop.admin_controller.payment_provider:getConfigAction'}

coreshop_admin_configuration_save_all:
    path: /%coreshop.admin.route.base%/configurations/save-all
    defaults: { _controller: 'coreshop.admin_controller.configuration:saveAllAction'}

coreshop_admin_configuration_get_all:
    path: /%coreshop.admin.route.base%/configurations/get-all
    defaults: { _controller: 'coreshop.admin_controller.configuration:getAllAction'}

coreshop_admin_settings_get_settings:
    path: /%coreshop.admin.route.base%/settings/get-settings
    methods: [GET]
    defaults:  { _controller: coreshop.admin_controller.settings:getSettingsAction }

coreshop_admin_report_get_data:
    path: /%coreshop.admin.route.base%/report/get-data
    methods: [GET]
    defaults:  { _controller: coreshop.admin_controller.reports:getReportDataAction}

coreshop_admin_report_export:
    path: /%coreshop.admin.route.base%/report/export
    methods: [GET]
    defaults:  { _controller: coreshop.admin_controller.reports:exportReportCsvAction}

coreshop_admin_portlet_get_data:
    path: /%coreshop.admin.route.base%/portlet/get-data
    methods: [GET]
    defaults:  { _controller: coreshop.admin_controller.portlets:getPortletDataAction}

coreshop_admin_report_portlet:
    path: /%coreshop.admin.route.base%/portlet/export
    methods: [GET]
    defaults:  { _controller: coreshop.admin_controller.portlets:exportPortletCsvAction}

coreshop_admin_settings_get:
    path: /%coreshop.admin.route.base%/settings/get
    methods: [GET]
    defaults:  { _controller: coreshop.admin_controller.settings:getAction }

coreshop_admin_settings_set:
    path: /%coreshop.admin.route.base%/settings/set
    methods: [POST]
    defaults:  { _controller: coreshop.admin_controller.settings:setAction }

coreshop_admin_purchasable_store_preview:
    path: /%coreshop.admin.route.base%/preview
    methods: [GET]
    defaults:  { _controller: coreshop.admin_controller.product_preview:previewAction}
