payum_all:
  resource: "@PayumBundle/Resources/config/routing/all.xml"

coreshop_admin_payment_provider_config:
  path: /%coreshop.admin.route.base%/payment_providers/get-config
  defaults: { _controller: 'coreshop.admin_controller.payment_provider:getConfigAction'}

coreshop_admin_configuration_save_all:
  path: /%coreshop.admin.route.base%/configurations/save-all
  defaults: { _controller: 'coreshop.admin_controller.configuration:saveAllAction'}

coreshop_admin_configuration_get_all:
  path: /%coreshop.admin.route.base%/configurations/get-all
  defaults: { _controller: 'coreshop.admin_controller.configuration:getAllAction'}

coreshop_admin_settings_get_settings:
  path: /%coreshop.admin.route.base%/settings/get-settings
  methods: [GET]
  defaults:  { _controller: coreshop.admin_controller.settings:getSettingsAction }

coreshop_admin_settings_get:
  path: /%coreshop.admin.route.base%/settings/get
  methods: [GET]
  defaults:  { _controller: coreshop.admin_controller.settings:getAction }

coreshop_admin_settings_set:
  path: /%coreshop.admin.route.base%/settings/set
  methods: [POST]
  defaults:  { _controller: coreshop.admin_controller.settings:setAction }
