pimcore:
    security:
        encoder_factories:
            '%coreshop.model.customer.class%': coreshop.security.customer.password_encoder_factory

security:
    providers:
        coreshop_customer:
            id: coreshop.security.customer.user_provider

    firewalls:
        coreshop_frontend:
            anonymous: ~
            context: shop
            form_login:
                login_path: coreshop_shop_login
                check_path: coreshop_shop_login_check
                provider: coreshop_customer
                failure_path: coreshop_shop_login
                default_target_path: coreshop_shop_index
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%secret%"
                name: APP_CORESHOP_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: coreshop_shop_logout
                target: coreshop_shop_login
                invalidate_session: false


#http://stackoverflow.com/questions/11602337/how-to-change-role-hierarchy-storage-in-symfony2