core_shop_resource:
    state_machine:
        callbacks:
            coreshop_order:
                after:
                    hold_inventory:
                        on: ['create']
                        do: ['@coreshop.inventory.order_operator', 'hold']
                        args: ['object']
                    cancel_inventory:
                        on: ['cancel']
                        do: ['@coreshop.inventory.order_operator', 'cancel']
                        args: ['object']
            coreshop_order_payment:
                after:
                    sell_inventory:
                        on: ['pay']
                        do: ['@coreshop.inventory.order_operator', 'sell']
                        args: ['object']