core_shop_product:
  pimcore:
    category:
      classes:
        repository: CoreShop\Bundle\CoreBundle\Pimcore\Repository\CategoryRepository
    product:
      classes:
        repository: CoreShop\Bundle\CoreBundle\Pimcore\Repository\ProductRepository