core_shop_customer:
  pimcore:
    customer_group:
      path: coreshop/customer_groups
      classes:
        install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomerGroup.json'
    customer:
      path: coreshop/customers
      classes:
        install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json'