core_shop_order:
  pimcore:
    cart:
      path: coreshop/carts
      classes:
        install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCart.json'
    cart_item:
      classes:
        install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCartItem.json'
    order:
      path: coreshop/orders
      classes:
        pimcore_controller: CoreShop\Bundle\CoreBundle\Controller\OrderController
        install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json'
    order_shipment:
      classes:
        install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipment.json'
    quote:
      path: coreshop/quotes
      classes:
        install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuote.json'
