framework:
  workflows:
    coreshop_order_payment:
      type: 'state_machine'
      marking_store:
        service: coreshop.state_machine.marking_store.order_payment_pimcore_marketing_store
      supports: CoreShop\Component\Core\Model\Order
      places:
          - new
          - awaiting_payment
          - partially_paid
          - cancelled
          - paid
          - partially_refunded
          - refunded
      transitions:
        request_payment:
          from: new
          to: awaiting_payment
        partially_pay:
          from: [awaiting_payment, partially_paid]
          to: partially_paid
        cancel:
          from: [awaiting_payment]
          to: cancelled
        pay:
          from: [awaiting_payment, partially_paid]
          to: paid
        partially_refund:
          from: [paid, partially_paid, partially_refunded]
          to: partially_refunded
        refund:
          from: [paid, partially_paid, partially_refunded]
          to: refunded

core_shop_resource:
  state_machine:
    callbacks:
      coreshop_order_payment:
        after:
          order_paid:
            on: ['pay']
            do: ['@coreshop.inventory.order_operator', 'sell']
            args: ['object']
          resolve_state:
            on: ['pay']
            do: ['@coreshop.state_machine_resolver.order', 'resolve']
            args: ['object']