framework:
  workflows:
    coreshop_order:
      type: 'state_machine'
      marking_store:
        service: coreshop.state_machine.marking_store.order_pimcore_marketing_store
      supports: CoreShop\Component\Core\Model\Order
      places:
          - initialized
          - new
          - cancelled
          - complete
      transitions:
        create:
          from: [initialized]
          to: new
        cancel:
          from: new
          to:   cancelled
        complete:
          from: new
          to:   complete


core_shop_resource:
  state_machine:
    callbacks:
      coreshop_order:
        after:
          request_payment:
            on: ['create']
            do: ['@coreshop.state_machine_cascade_transition', 'apply']
            args: ['object', 'event', '"request_payment"', '"coreshop_order_payment"']
          hold_inventory:
            on: ['create']
            do: ['@coreshop.inventory.order_operator', 'hold']
            args: ['object']
          cancel_payment:
            on: ['cancel']
            do: ['@coreshop.state_machine_cascade_transition', 'apply']
            args: ['object.getPayments()', 'event', '"cancel"', '"coreshop_payment"']
          cancel_order_payment:
            on: ['cancel']
            do: ['@coreshop.state_machine_cascade_transition', 'apply']
            args: ['object', 'event', '"cancel"', '"coreshop_order_payment"']