CoreShop\Component\Core\Model\Store:
  exclusion_policy: ALL
  xml_root_name: store
  properties:
    baseCurrency:
      expose: true
      type: relation
      groups: [List, Detailed]
    baseCountry:
      expose: true
      type: relation
      groups: [List, Detailed]
