CoreShop\Component\Core\Model\Store:
    exclusion_policy: ALL
    xml_root_name: store
    properties:
        baseCountry:
            expose: true
            type: relation
            groups: [List, Detailed]
        countries:
            expose: true
            type: relation
            groups: [List, Detailed]
        useGrossPrice:
            expose: true
            type: boolean
            groups: [List, Detailed]
