CoreShop\Bundle\OrderBundle\DTO\AddToCart:
    constraints:
        - \CoreShop\Bundle\CoreBundle\Validator\Constraints\AddToCartAvailability: { message: 'coreshop.cart_item.not_sufficient_stock', groups: ['coreshop'] }
