CoreShop\Component\Core\Model\Customer:
    constraints:
        -   \CoreShop\Bundle\CoreBundle\Validator\Constraints\UniqueCustomer:
                groups: [ coreshop ]
                messageEmail: coreshop.form.customer.email.unique
                messageUsername: coreshop.form.user.username.unique
