CoreShop\Component\Core\Model\Customer:
    constraints:
        -   \CoreShop\Bundle\CoreBundle\Validator\Constraints\UniqueCustomer:
                groups: [ coreshop ]
                messageEmail: coreshop.form.customer.email.unique
                messageUsername: coreshop.form.user.username.unique

        -   \CoreShop\Bundle\CoreBundle\Validator\Constraints\RegisteredUser:
                groups: [ coreshop_customer_guest ]
                message: coreshop.form.customer.email.registered
