core_shop_order:
    pimcore:
        order:
            path:
                order: coreshop/orders
                cart: coreshop/carts
                quote: coreshop/quotes
            classes:
                pimcore_controller:
                    default: CoreShop\Bundle\CoreBundle\Controller\OrderController
                    creation: CoreShop\Bundle\CoreBundle\Controller\OrderCreationController
                install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json'
                interface: CoreShop\Component\Core\Model\OrderInterface
        order_item:
            classes:
                install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json'
                interface: CoreShop\Component\Core\Model\OrderItemInterface
        order_shipment:
            classes:
                install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipment.json'
                interface: CoreShop\Component\Core\Model\OrderShipmentInterface
        order_shipment_item:
            classes:
                install_file: '@CoreShopCoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipmentItem.json'
                interface: CoreShop\Component\Core\Model\OrderShipmentItemInterface