core_shop_tier_pricing:
    resources:
        product_tier_price_range:
            classes:
                model: CoreShop\Component\Core\Model\ProductTierPriceRange
    action_constraints:
        -
            class: 'CoreShop\Bundle\CoreBundle\Validation\Constraints\TierPriceRangeCurrencyAware'
            groups:
                - 'coreshop_tier_pricing_range_validation_behaviour_fixed'
                - 'coreshop_tier_pricing_range_validation_behaviour_amount_decrease'
                - 'coreshop_tier_pricing_range_validation_behaviour_amount_increase'
